FROM px4io/px4-dev-ros-kinetic

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update && \
    apt-get upgrade -y &&\
    apt-get install -y sudo git wget vim tmux python3-pip &&
    apt clean

RUN adduser --disabled-password --gecos "" dev &&\
    echo "dev ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/dev

USER dev
ENV HOME /home/dev
WORKDIR  /home/dev

ADD vimrc     $HOME/.vimrc
ADD bashrc    $HOME/.bashrc
ADD tmux.conf $HOME/.tmux.conf

RUN sudo chown dev:dev $HOME/.vimrc $HOME/.bashrc $HOME/.tmux.conf &&\
    sudo chmod 644 $HOME/.vimrc $HOME/.bashrc $HOME/.tmux.conf

RUN mkdir -p ~/.vim/autoload/ &&\
    wget -O ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim &&\
    vim +'PlugInstall --sync' +qa

RUN echo 'source /opt/ros/kinetic/setup.bash' >> $HOME/.bashrc

RUN source $HOME/.bashrc &&\
    pip3 install --user git+git://github.com/powerline/powerline

CMD ["tmux", "-2u"]





